DROP TABLE IF EXISTS answers CASCADE;
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  given_answer VARCHAR(120),
  attempt_id INTEGER REFERENCES attempts(id) ON DELETE CASCADE
);
